#!/bin/sh
export BinHome==$(cd $(dirname $0) && pwd)
export PATH=$PATH:$BinHome
 
ingeo=$1
outgeo=$2
taskpara=$3
othertask="$4 $5 $6"
inext=${ingeo##*.}
inbase=${ingeo%.*}

if [[ "$#" == 0 || "$1" =~ help ]] ; then 
    echo "Example: g2g a.vasp b.pw"
    exit 0
elif [[ ! -s "$ingeo" && ! "$ingeo" =~ qepath ]]  ; then 
    echo "$ingeo not exist!" 
    exit 1
fi
 
 
if [[ "$outgeo" =~ slab$ ]] ; then 
    python  $BinHome/slabcut.py $ingeo
elif [[ "$outgeo" =~ vaspkp$ ]] ; then 
    python  $BinHome/vaspkp.py $ingeo
elif [[ "$ingeo" =~ qepath ]] ; then    
   QEBINHOME=$2
   export PATH=$PATH:$QEBINHOME/mpi:$QEBINHOME/qe
elif [[ "$ingeo" =~ gjf$ ]] && [[ -z "$outgeo" || "$outgeo" =~ xyz$ ]] ; then
   [[ -z "$outgeo" ]] && outgeo=${inbase}.xyz
   gjf2xyz $ingeo $outgeo
elif [[ "$ingeo" =~ vasp$ || "$ingeo" =~ POSCA || "$ingeo" =~ CONTCA ]] && [[ -z "$outgeo" || "$outgeo" =~ pw$ ]] ; then 
   [[ -z "$outgeo" ]] && outgeo=$(basename $ingeo .vasp).pw
   v2qe $ingeo $outgeo
elif [[ "$ingeo" =~ out$ || "$ingeo" =~ ^espresso.log || "$ingeo" =~ pw$ || "$ingeo" =~ in$ ]] ; then 
   if [[ "$outgeo" =~ xsf$ ]] ; then 
      qe2xsf $ingeo $outgeo 
   elif [[ "$outgeo" =~ xyz$ ]] ; then 
      qe2xyz $ingeo $outgeo ${taskpara}
   elif [[ "$outgeo" =~ cif$ ]] ; then 
      qe2xsf $ingeo g2gtmp.xsf 2>/dev/null
      obabel.exe g2gtmp.xsf -Og2gtmp.tmp.vasp
      obabel.exe g2gtmp.tmp.vasp -O$outgeo 2>/dev/null
       sed -i  "/_symmetry_equiv_pos_as_xyz/,/loop_/ d" ${outgeo}
       sed -i "s/^ *_space_group_name_H-M_alt.*$/_space_group_name_H-M_alt 'P 1'/g" ${outgeo}
       sed -i "s/^ *_space_group_name_Hall.*$/_space_group_name_Hall 'P 1'/g" ${outgeo}
       sed -i "/loop_/iloop_\n   _symmetry_equiv_pos_as_xyz\n    x,y,z\n" ${outgeo}
   elif [[ "$outgeo" =~ pw$ ]] ; then    
      qe2xsf $ingeo g2gtmp.xsf 2>/dev/null
      obabel.exe g2gtmp.xsf -ovasp -Og2gtmp.vasp
      v2qe g2gtmp.vasp $outgeo  
   elif [[ "$outgeo" =~ vasp$ || "$outgeo" =~ POSCA  ]] ; then  
      qe2xsf $ingeo g2gtmp.xsf 2>/dev/null
      obabel.exe g2gtmp.xsf -ovasp -O$outgeo
   else
      qe2xsf $ingeo ${inbase}.xsf 
   fi
elif [[ "$ingeo" =~ hzw$ ]] ; then 
   if [[ "$outgeo" =~ xsf$ ]] ; then 
       hzw2xsf $ingeo $outgeo  
   elif [[ "$outgeo" =~ cif$ ]] ; then  
       hzw2xsf $ingeo   g2gtmp.xsf
       obabel.exe g2gtmp.xsf -Og2gtmp.tmp.cif
       obabel.exe g2gtmp.tmp.cif -O$outgeo 2>/dev/null
       sed -i "/_symmetry_equiv_pos_as_xyz/,/loop_/ d" ${outgeo}
       sed -i "s/^ *_space_group_name_H-M_alt.*$/_space_group_name_H-M_alt 'P 1'/g" ${outgeo}
       sed -i "s/^ *_space_group_name_Hall.*$/_space_group_name_Hall 'P 1'/g" ${outgeo}
       sed -i "/loop_/iloop_\n   _symmetry_equiv_pos_as_xyz\n    x,y,z\n" ${outgeo}
   elif [[ "$outgeo" =~ vasp$ || "$outgeo" =~ POSCA || "$outgeo" =~ CONTCA ]] ; then  
       hzw2xsf $ingeo   g2gtmp.xsf
       obabel.exe g2gtmp.xsf -ovasp -O$outgeo
   else
       hzw2xsf $ingeo   g2gtmp.xsf
       obabel.exe g2gtmp.xsf -ovasp -O${inbase}.vasp
   fi
elif [[ "$ingeo" =~ cif$ || "$ingeo" =~ pdb$ ]] ; then  
   if [[ "$outgeo" =~ pw$ ]] ; then
       obabel.exe $ingeo -ovasp -Og2gtmp.vasp  $addpara
       v2qe g2gtmp.vasp $outgeo
   elif [[ "$outgeo" =~ vasp$ || "$outgeo" =~ POSCA || "$outgeo" =~ CONTCA ]] ; then
       obabel.exe $ingeo -O$outgeo  $addpara  
   elif [[ "$outgeo" =~ cif$ ]] ; then 
       if [[ "$outgeo" =~ fill || "$outgeo" =~ full ]] ; then 
           [[ "$outgeo" == cif ]] && outgeo=${inbase}_full.cif
           obabel.exe $ingeo  -ocif -O${outgeo} --fillUC strict
       else
           [[ "$outgeo" == cif ]] && outgeo=${inbase}_nosym.cif
           sed   "/_symmetry_equiv_pos_as_xyz/,/loop_/ d" $ingeo > ${outgeo}
           sed -i "s/^ *_space_group_name_H-M_alt.*$/_space_group_name_H-M_alt 'P 1'/g" ${outgeo}
           sed -i "s/^ *_space_group_name_Hall.*$/_space_group_name_Hall 'P 1'/g" ${outgeo}
           sed -i "/loop_/iloop_\n   _symmetry_equiv_pos_as_xyz\n    x,y,z\n" ${outgeo}
           echo "$outgeo generated!"
       fi
   else
       obabel.exe $ingeo -ovasp -Og2gtmp.vasp 
       v2qe g2gtmp.vasp  ${inbase}.pw
   fi
elif [[ "$ingeo" =~ axsf$ ]] ; then 
   if [[ "$outgeo" =~ xsf$ ]] ; then
       vib2xsf $ingeo ${taskpara} ${otherpara}
       mv qe2vib${taskpara}x*.xsf $outgeo 
   else
       xsf2xyz $ingeo  $outgeo
   fi
elif [[ "$outgeo" =~ pw$ ]] ; then  
   obabel.exe $ingeo -Og2gtmp.vasp
   v2qe g2gtmp.vasp $outgeo
elif [[ "$outgeo" =~ xsf$ ]] ; then
   obabel.exe $ingeo -Og2gtmp.vasp
   v2qe g2gtmp.vasp g2gtmp.pw 
   qe2xsf g2gtmp.pw $outgeo
elif [[ "$outgeo" =~ vasp$ || "$outgeo" =~ POSCA || "$outgeo" =~ CONTCA ]] ; then
   obabel.exe $ingeo -ovasp -O$outgeo
else
   obabel.exe $ingeo -O$outgeo
fi  
 
rm -f g2gtmp.* qe2vib*x*.xsf 2>/dev/null 
exit 0
