#!/bin/sh
if [[ "$#" == "0" ]] ; then 
 ingjf=$( ls -t *.gjf 2>/dev/null|head -1)
[[ -z "$ingjf" ]] && echo "No gjf file exitst! " && exit 1
else
ingjf=$1
outxyz=$2
fi

[[ ! -s $ingjf || ! "$ingjf" =~ gjf$ ]] && echo "$ingjf not exist or not a gjf file!"  && exit 2
base=$( echo $ingjf| rev |cut -c 5-|rev)
[[ -z "$outxyz" ]] && outxyz=${base}.xyz
carxyz=$( awk '(NF==4 && length($1)<3 && length($1>0) && $1~/^[A-Za-z]+$/&&$2~/^[0-9.-]+$/&&$3~/^[0-9.-]+$/&&$4~/^[0-9.-]+$/) ' $ingjf )
if [[ -z "$carxyz" ]] ; then
carxyz=$( awk <$ingjf '
@include "eletable.awk" 
BEGIN{eletable();} 
{if ( NF==4 && length($1)<3 && length($1)>0 && $1~/^[0-9]+$/&&$2~/^[0-9.-]+$/&&$3~/^[0-9.-]+$/&&$4~/^[0-9.-]+$/){print mysymbol[$1],$2,$3,$4 }
}')
 fi
natom=$(echo "$carxyz"|awk '{natom=NR;}END{print natom;}')
echo "$natom" >$outxyz
echo "" >> $outxyz
echo "$carxyz" >> $outxyz 
echo "$outxyz generated!"
exit 0



