#!/bin/sh
#"------------------------------------------";    
#"--------------  qe otput to XYZ  ---------";
#"--------   Written by Yuewen Mu ----------";
#"------------------------------------------";
## export AWKPATH=${soft_root}/libadd/awklib
if [[ "$#" == "1" ]] ; then
   qeout=$1
   outxyz=$(echo $qeout |rev|cut -c 4-|rev).xsf
elif [[ "$#" -ge "2" ]] ; then
   qeout=$1
   outxyz=$2
   nskip=$3
else
echo "Example: pw2xsf scf.in/scf.out b.xsf"   
fi
[[ -z "$qeout" || ! -s  "$qeout" ]] && echo "QE outfile not exist!" && exit 1
[[ -z "$nskip" || "$nskip" == 0 ]] && nskip=2

awk -v qeout="$qeout"  -v outxyz=$outxyz -v nskip=$nskip '
BEGIN{  
bohr=0.529177249;
alat=1.0;
geoid=0;
while((getline<qeout) != NULL){
if ($0~/number of atom.*cell/){
  natom=$NF;
}else if ($0~/lattice parameter.*alat.*a.u./){
  alat=$(NF-1);
}else if($0~/number of atomic types/){
  nty=$NF;
}else if($0~/^! *total energy *=/){
  geoid=geoid+1;
  Etot=$(NF-1);
  if(nskip == 1 || geoid%nskip == 1){
      print natom >outxyz;
      print Etot >outxyz;
      for (i=1;i<=natom;i++){
          printf "%-5s%15.10f%15.10f%15.10f\n", sele[i],cxyz[i,1],cxyz[i,2],cxyz[i,3]  >outxyz;
      }
  }
}else if($0~/lattice parameter/){
  sf=$(NF-1);
}else if($0 ~/crystal axes:.*coord.*alat/ ) {
  for (i=1; i<=3; i++){
    getline<qeout;
    for(j=1;j<=3;j++){latt[i,j]=alat*bohr*$(j+3);}} 
}else if($0 ~/CELL_PARAMETERS.*alat/ ) {
  gsub(/)/,"",$NF);
  alat=$NF;
  for (i=1; i<=3; i++){
    getline<qeout;
    for(j=1;j<=3;j++){latt[i,j]=alat*bohr*$j;}} 
}else if($0 ~/CELL_PARAMETERS.*angstrom/ ) {
  for (i=1; i<=3; i++){
    getline<qeout;
    for(j=1;j<=3;j++){latt[i,j]=$j;}} 
}else if($0 ~/site.*atom.*positions.*cryst/ ) {
  for(i=1;i<=natom;i++){
    getline<qeout;
    sele[i]=$2;
    cxyz[i,1]=$7*latt[1,1]+$8*latt[2,1]+$9*latt[3,1];
    cxyz[i,2]=$7*latt[1,2]+$8*latt[2,2]+$9*latt[3,2];
    cxyz[i,3]=$7*latt[1,3]+$8*latt[2,3]+$9*latt[3,3];}
}else if($0 ~/ATOMIC_POSITIONS.*cryst/ ) {
  for(i=1;i<=natom;i++){
    getline<qeout;
    sele[i]=$1;
    cxyz[i,1]=$2*latt[1,1]+$3*latt[2,1]+$4*latt[3,1];
    cxyz[i,2]=$2*latt[1,2]+$3*latt[2,2]+$4*latt[3,2];
    cxyz[i,3]=$2*latt[1,3]+$3*latt[2,3]+$4*latt[3,3];
     }
}else if($0 ~/ATOMIC_POSITIONS.*angstrom/ ) {
  for(i=1;i<=natom;i++){
    getline<qeout;
    sele[i]=$1;
    cxyz[i,1]=$2;
    cxyz[i,2]=$3;
    cxyz[i,3]=$4;}
}else if($0 ~/site.*atom.*positions.*alat.*units/ ) {
  for(i=1;i<=natom;i++){
    getline<qeout;
    sele[i]=$2;
    cxyz[i,1]=$7*alat*bohr;
    cxyz[i,2]=$8*alat*bohr;
    cxyz[i,3]=$9*alat*bohr;}
}}
exit
}'
echo "Trace file $outxyz generated!"
exit 0
