#!/bin/sh
## export AWKPATH=${soft_root}/libadd/awklib

if [[ "$#" == "0" ]] ; then
read -p "Please enter POSCAR-like file: " inpos
read -p "Please enter .pw name: " outpw
elif [[ "$#" -ge 1  ]] ; then
inpos="$1"
outpw=$2
else
echo "Example: v2pw POSCAR a.pw"
exit 0
fi


[[ ! -s "$inpos" ]] && echo "$inpos not exist!" && exit 1
[[ -z "$outpw" ]] && outpw=$(basename ${inpos} .vasp).pw

awk -v inpos=$inpos -v outpw="$outpw" '
BEGIN{
getline< inpos ;
disp=$1;
getline< inpos ;
sf=$1;
for (i=1; i<=3; i++){
  getline<inpos;
  for(j=1;j<=3;j++){latt[i,j]=sf*$j;}}
getline<inpos;
nty=NF;
if ($1 ~/^[0-9]+$/){
natom=0;
for (i=1; i<=nty; i++){nele[i]=$i;natom=natom+$i;}
}else{
for (i=1; i<=nty; i++){ele[i]=$i;}
getline<inpos;
natom=0;
for (i=1; i<=nty; i++){nele[i]=$i;natom=natom+$i;}
}

getline<inpos;
if(substr($1,1,1)~/S/ || substr($1,1,1)~/s/){getline<inpos;}
if(substr($1,1,1)~/d/ || substr($1,1,1)~/D/){
   atomunit="crystal"
}else {
   atomunit="angstrom"
}
for (i=1;i<=natom;i++){
    getline<inpos;
    for (j=1;j<=3;j++){dxyz[i,j]=$j;}
}



k=0;
for(i=1;i<=nty;i++){
 for(j=k+1;j<=k+nele[i];j++){sele[j]=ele[i];}
  k=k+nele[i];}

printf "&SYSTEM\n" >outpw;
printf "nat=%d\n",natom >outpw;
printf "ibrav= 0\n" >outpw;
printf "/\n" >outpw;
printf "\n" >outpw;

printf "CELL_PARAMETERS angstrom\n" >outpw;
for (i=1; i<=3; i++){
    printf "%17.10f%17.10f%17.10f\n", latt[i,1],latt[i,2],latt[i,3] >outpw;}
 printf "\n" >outpw;

printf "ATOMIC_POSITIONS %s\n",atomunit >outpw;
for (i=1;i<=natom;i++){
	printf "%-5s%15.10f%15.10f%15.10f\n", sele[i],dxyz[i,1],dxyz[i,2],dxyz[i,3]  >outpw;
}
}'
clip.exe < $outpw
echo "$outpw generated!"
exit 0
